// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	dto "backend/src/internal/model/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "backend/src/internal/model"
)

// IEquipmentRepository is an autogenerated mock type for the IEquipmentRepository type
type IEquipmentRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) Add(ctx context.Context, request *dto.AddEquipmentRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.AddEquipmentRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) Delete(ctx context.Context, request *dto.DeleteEquipmentRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteEquipmentRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) Get(ctx context.Context, request *dto.GetEquipmentRequest) (*model.Equipment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentRequest) (*model.Equipment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentRequest) *model.Equipment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEquipmentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByReserve provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) GetByReserve(ctx context.Context, request *dto.GetEquipmentByReserveRequest) ([]*model.Equipment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByReserve")
	}

	var r0 []*model.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentByReserveRequest) ([]*model.Equipment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentByReserveRequest) []*model.Equipment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEquipmentByReserveRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStudio provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) GetByStudio(ctx context.Context, request *dto.GetEquipmentByStudioRequest) ([]*model.Equipment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByStudio")
	}

	var r0 []*model.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentByStudioRequest) ([]*model.Equipment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentByStudioRequest) []*model.Equipment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEquipmentByStudioRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFullTimeFreeByStudioAndType provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) GetFullTimeFreeByStudioAndType(ctx context.Context, request *dto.GetEquipmentFullTimeFreeByStudioAndTypeRequest) ([]*model.Equipment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetFullTimeFreeByStudioAndType")
	}

	var r0 []*model.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentFullTimeFreeByStudioAndTypeRequest) ([]*model.Equipment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentFullTimeFreeByStudioAndTypeRequest) []*model.Equipment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEquipmentFullTimeFreeByStudioAndTypeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotFullTimeFreeByStudioAndType provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) GetNotFullTimeFreeByStudioAndType(ctx context.Context, request *dto.GetEquipmentNotFullTimeFreeByStudioAndTypeRequest) ([]*dto.EquipmentAndTime, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetNotFullTimeFreeByStudioAndType")
	}

	var r0 []*dto.EquipmentAndTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentNotFullTimeFreeByStudioAndTypeRequest) ([]*dto.EquipmentAndTime, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEquipmentNotFullTimeFreeByStudioAndTypeRequest) []*dto.EquipmentAndTime); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.EquipmentAndTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEquipmentNotFullTimeFreeByStudioAndTypeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *IEquipmentRepository) Update(ctx context.Context, request *dto.UpdateEquipmentRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateEquipmentRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIEquipmentRepository creates a new instance of IEquipmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the pool expectations.
// The first argument is typically a *testing.T value.
func NewIEquipmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEquipmentRepository {
	mock := &IEquipmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
