// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	dto "backend/src/internal/model/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "backend/src/internal/model"
)

// IStudioRepository is an autogenerated mock type for the IStudioRepository type
type IStudioRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, request
func (_m *IStudioRepository) Add(ctx context.Context, request *dto.AddStudioRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.AddStudioRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, request
func (_m *IStudioRepository) Delete(ctx context.Context, request *dto.DeleteStudioRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteStudioRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, request
func (_m *IStudioRepository) Get(ctx context.Context, request *dto.GetStudioRequest) (*model.Studio, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Studio
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetStudioRequest) (*model.Studio, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetStudioRequest) *model.Studio); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Studio)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetStudioRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, request
func (_m *IStudioRepository) GetAll(ctx context.Context, request *dto.GetStudioAllRequest) ([]*model.Studio, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.Studio
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetStudioAllRequest) ([]*model.Studio, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetStudioAllRequest) []*model.Studio); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Studio)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetStudioAllRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *IStudioRepository) Update(ctx context.Context, request *dto.UpdateStudioRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateStudioRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIStudioRepository creates a new instance of IStudioRepository. It also registers a testing interface on the mock and a cleanup function to assert the pool expectations.
// The first argument is typically a *testing.T value.
func NewIStudioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStudioRepository {
	mock := &IStudioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
